animesite/animesite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from animesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('news.urls', namespace='news')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"

animesite/news/urls.py
from django.urls import path

from news import views

app_name = 'news'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('post/<slug:post_slug>/', views.PostPageView.as_view(), name='post_page'),
]

animesite/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login_user'),
    path('logout/', LogoutView.as_view(), name='logout_user'),

    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('registration_success/', views.registration_success, name='registration_success'),

    path('user_profile/', views.UserProfile.as_view(), name='user_profile'),

    path('user_profile/password_change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('user_profile/password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
                                            template_name='users/password_reset_form.html',
                                            email_template_name='users/password_reset_email.html',
                                            success_url=reverse_lazy('users:password_reset_done')
                                            ),
                                            name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
                                            template_name='users/password_reset_done.html'),
                                            name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                            template_name='users/password_reset_confirm.html',
                                            success_url=reverse_lazy('users:password_reset_complete')
                                            ),
                                            name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(
                                            template_name='users/password_reset_complete.html'),
                                            name='password_reset_complete'),
]

animesite/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True, verbose_name='Аватар')
    birth_date = models.DateField(blank=True, null=True, verbose_name='Дата рождения')

animesite/users/forms.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django import forms


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegistrationUserForm(UserCreationForm):
    ''' форма регистрации нового пользователя '''

    username = forms.CharField(label="Логин")
    password1 = forms.CharField(label="Пароль")
    password2 = forms.CharField(label="Повтор пароля")

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def clean_email(self):
        ''' проверка наличия е-мейл адреса в системе при регистрации нового пользователя,
         если таковой уже существует, вызывается исключение '''

        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой e-mail уже используется!")
        return email


class ProfileUserForm(forms.ModelForm):
    ''' форма отображения профиля пользователя '''

    username = forms.CharField(disabled=True, label="Логин")
    email = forms.CharField(disabled=True, label="E-mail")
    date_joined = forms.DateTimeField(disabled=True, label='Зарегистирован(а)')

    this_year = datetime.date.today().year
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))), label='Дата рождения')

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name', 'birth_date', 'date_joined']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserPasswordChangeForm(PasswordChangeForm):
    ''' форма для смены пароля пользователя '''

    old_password = forms.CharField(label="Старый пароль")
    new_password1 = forms.CharField(label="Новый пароль")
    new_password2 = forms.CharField(label="Повтор пароля")

animesite/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from animesite import settings
from users.forms import LoginUserForm, RegistrationUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUserView(LoginView):
    ''' авторизация '''
    form_class = LoginUserForm
    template_name = 'users/login_user.html'
    extra_context = {'title': 'Авторизация'}


class RegistrationUserView(CreateView):
    ''' регистрация '''
    form_class = RegistrationUserForm
    template_name = 'users/registration.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:registration_success')


def registration_success(request):
    ''' что увидит пользователь после успешной регистрации '''
    return render(request, 'users/registration_success.html')


class UserProfile(LoginRequiredMixin, UpdateView):
    '''отображение страницы с профилем пользователя'''

    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/user_profile.html'
    extra_context = {
        'title': 'Профиль пользователя',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:user_profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    '''класс для смены пароля пользователя.
    унаследован от базового PasswordChangeView,
    изменена только ссылка переадресации success_url,
     т.к. требуется дополнительно указать пространство имен users '''

    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'

animesite/users/templates/users/login_user.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>Авторизация</h1>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit">Войти</button></p>

            <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
        </form>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_change.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
  <div class="form-table-panel">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Изменить</button>
    </form>
  </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h2>Пароль успешно изменен!</h2>

        <p>Вы успешно изменили пароль. <a href="{% url 'users:user_profile' %}">Вернуться в профиль</a></p>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
      <h1>Восстановление пароля</h1>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit">Сбросить по E-mail</button></p>
      </form>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>Пароль изменен</h1>

        <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login_user' %}">входа в систему</a></p>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>Новый пароль</h1>

        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <p><button type="submit">Сохранить</button></p>
        </form>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <p>Сброс пароля</p>

        <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

        <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </div>
</div>
{% endblock %}

animesite/users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}

{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock reset_link %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

animesite/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
      <h1>Восстановление пароля</h1>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit">Сбросить по E-mail</button></p>
      </form>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/registration.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>Регистрация</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit">Регистрация</button></p>
        </form>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/registration_success.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>Регистрация прошла успешно!</h1>

        <p><a href="{% url 'users:login_user' %}">Авторизуйтесь</a>, чтобы продолжить работу.</p>
    </div>
</div>
{% endblock content %}

animesite/users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% if user.photo %}
            <p><img src="{{ user.photo.url }}" width="200"></p>
            {% else %}
            <p><img src="{{ default_image }}" width="200"></p>
            {% endif %}

            {{ form.as_p }}
            <button type="submit">Сохранить</button>

            <p><a href="{% url 'users:password_change' %}">Сменить пароль</p>
        </form>
    </div>
</div>
{% endblock content %}