animesite/anime/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('anime/', views.AllAnimePageView.as_view(), name='all_anime_page'),
    path('anime/add/', views.AddNewAnimeView.as_view(), name='add_new_anime'),
    path('anime/edit/<slug:anime_slug>/', views.EditAnimeView.as_view(), name='edit_anime'),
    path('anime/<slug:anime_slug>/', views.AnimePageView.as_view(), name='anime_page'),
    path('genre/', views.GenrePageView.as_view(), name='genre_page'),
    path('genre/add/', views.AddNewGenreView.as_view(), name='add_new_genre'),
    path('genre/edit/<slug:genre_slug>/', views.EditGenreView.as_view(), name='edit_genre'),
    path('genre/<slug:genre_slug>/', views.AnimeFromGenrePageView.as_view(), name='anime_from_genre_page'),
    path('year/', views.YearsPageView.as_view(), name='year_page'),
    path('year/add/', views.AddNewYearView.as_view(), name='add_new_year'),
    path('year/edit/<slug:year>/', views.EditYearView.as_view(), name='edit_year'),
    path('year/<int:year>/', views.AnimeFromYearPageView.as_view(), name='anime_from_year_page'),
    path('producer/add/', views.AddNewProducerView.as_view(), name='add_new_producer'),
    path('producer/edit/<slug:producer_slug>/', views.EditProducerView.as_view(), name='edit_producer'),
    path('producer/<slug:producer_slug>/', views.AnimeFromProducerPageView.as_view(), name='anime_from_producer_page'),
    path('author/add/', views.AddNewAuthorView.as_view(), name='add_new_author'),
    path('author/edit/<slug:author_slug>/', views.EditAuthorView.as_view(), name='edit_author'),
    path('author/<slug:author_slug>/', views.AnimeFromAuthorPageView.as_view(), name='anime_from_author_page'),
    path('tag/add/', views.AddNewTagView.as_view(), name='add_new_tag'),
    path('tag/edit/<slug:tag_slug>/', views.EditTagView.as_view(), name='edit_tag'),
    path('tag/<slug:tag_slug>/', views.AnimeFromTagPageView.as_view(), name='anime_from_tag_page'),
    path('studio/', views.StudioPageView.as_view(), name='studio_page'),
    path('studio/add/', views.AddNewStudioView.as_view(), name='add_new_studio'),
    path('studio/edit/<slug:studio_slug>/', views.EditStudioView.as_view(), name='edit_studio'),
    path('studio/<slug:studio_slug>/', views.AnimeFromStudioPageView.as_view(), name='anime_from_studio_page'),
]

animesite/animesite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from animesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('news.urls', namespace='news')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"

animesite/news/urls.py
from django.urls import path

from news import views

app_name = 'news'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('post/<slug:post_slug>/', views.PostPageView.as_view(), name='post_page'),
]

animesite/anime/models.py
from autoslug import AutoSlugField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Anime(models.Model):
    name_ru = models.CharField(max_length=255, verbose_name="Заголовок на русском")
    name_en = models.CharField(max_length=255, verbose_name="Заголовок на английском")
    name_jp = models.CharField(max_length=255, verbose_name="Заголовок на японском")
    anime_slug = AutoSlugField(populate_from='name_jp', unique=True, db_index= True, verbose_name="Слаг")
    image = models.ImageField(upload_to="image/%Y/%m/%d/", default=None, blank=True, null=True, verbose_name="Обложка")
    genre = models.ManyToManyField("Genre", related_name="genre", verbose_name="Жанр")
    episodes = models.IntegerField(default=1, verbose_name="Количество эпизодов")
    year = models.ForeignKey(to="Years", on_delete=models.PROTECT, related_name="years", verbose_name="Год выхода")
    producer = models.ManyToManyField("Producer", blank=True, related_name="producer", verbose_name="Режиссер")
    author = models.ForeignKey(to="Author", on_delete=models.PROTECT, related_name="author", verbose_name="Автор оригинала")
    tag = models.ManyToManyField("Tag", related_name="tags", verbose_name="Теги")
    studio = models.ManyToManyField("Studio", related_name="studio", verbose_name="Студия-издатель")
    description = models.TextField(verbose_name="Описание")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_anime", verbose_name="Добавлено")

    class Meta:
        verbose_name = "Аниме"
        verbose_name_plural = "Аниме"
        ordering = ("name_ru", )

    def __str__(self):
        return self.name_ru

    def get_absolute_url(self):
        return reverse('anime_page', kwargs={'anime_slug': self.anime_slug})


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="Жанр")
    genre_slug = AutoSlugField(populate_from='name', unique=True, db_index=True, verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_genre", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('anime_from_genre_page', kwargs={'genre_slug': self.genre_slug})

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"
        ordering = ("name", )


class Years(models.Model):
    year = models.IntegerField(default=2000, verbose_name="Год издания")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_year", verbose_name="Добавлено")

    def __str__(self):
        return str(self.year)

    def get_absolute_url(self):
        return reverse('anime_from_year_page', kwargs={'year': self.year})

    class Meta:
        verbose_name = "Год"
        verbose_name_plural = "Годы"
        ordering = ("year", )


class Author(models.Model):
    name = models.CharField(max_length=255,  verbose_name="Имя")
    author_slug = AutoSlugField(populate_from="name", unique=True, db_index=True,  verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_author", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('anime_from_author_page', kwargs={'author_slug': self.author_slug})

    class Meta:
        verbose_name = "Автор оригинала"
        verbose_name_plural = "Авторы оригиналов"
        ordering = ("name", )


class Producer(models.Model):
    name = models.CharField(max_length=100,  verbose_name="Имя")
    producer_slug = AutoSlugField(populate_from="name", unique=True, db_index=True,  verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_producer", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('anime_from_producer_page', kwargs={'producer_slug': self.producer_slug})

    class Meta:
        verbose_name = "Режиссер"
        verbose_name_plural = "Режиссеры"
        ordering = ("name", )


class Studio(models.Model):
    name = models.CharField(max_length=100,  verbose_name="Название")
    studio_slug = AutoSlugField(populate_from="name", unique=True, db_index=True,  verbose_name="Слаг")
    logo = models.ImageField(upload_to="logo/%Y/%m/%d/", verbose_name="Логотип")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None,  related_name="add_studio", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('anime_from_studio_page', kwargs={'studio_slug': self.studio_slug})

    class Meta:
        verbose_name = "Студия"
        verbose_name_plural = "Студии"
        ordering = ("name", )


class Tag(models.Model):
    tag = models.CharField(max_length=100,  verbose_name="Teг")
    tag_slug = AutoSlugField(populate_from="tag", unique=True, db_index=True,  verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_tag", verbose_name="Добавлено")

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('anime_from_tag_page', kwargs={'tag_slug': self.tag_slug})

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"
        ordering = ("tag", )


class Character(models.Model):
    name = models.CharField(max_length=255,  verbose_name="Имя")
    seiyuu = models.ForeignKey(to="Seiyuu", on_delete=models.PROTECT, verbose_name="Слаг")
    description = models.TextField()
    character_slug = AutoSlugField(populate_from="name", unique=True, db_index=True, verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_character", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Персонаж"
        verbose_name_plural = "Персонажи"
        ordering = ("name", )


class Seiyuu(models.Model):
    name = models.CharField(max_length=255,  verbose_name="Имя")
    seiyuu_slug = AutoSlugField(populate_from="name", unique=True, db_index=True,  verbose_name="Слаг")
    action = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name="add_seiyuu", verbose_name="Добавлено")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Сейю"
        verbose_name_plural = "Сейю"
        ordering = ("name", )

animesite/anime/forms.py
from django import forms

from anime.models import Anime, Genre, Years, Producer, Author, Tag, Studio


class AddAnimeForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить новое аниме '''

    class Meta:
        model = Anime
        fields = ['name_ru', 'name_en', 'name_jp', 'image', 'genre', 'episodes', 'year', 'producer', 'author', 'tag', 'studio', 'description']


class AddNewGenreForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить новый жанр '''

    class Meta:
        model = Genre
        fields = ['name', ]


class AddNewYearForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить новый год '''

    class Meta:
        model = Years
        fields = ['year', ]


class AddNewProducerForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить новый режиссера '''

    class Meta:
        model = Producer
        fields = ['name', ]


class AddNewAuthorForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить нового автора оригинала '''

    class Meta:
        model = Author
        fields = ['name', ]


class AddNewTagForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить нового тега '''

    class Meta:
        model = Tag
        fields = ['tag', ]


class AddNewStudioForm(forms.ModelForm):
    ''' форма позволяет внести данные, чтобы добавить новую студию '''

    class Meta:
        model = Studio
        fields = ['name', 'logo']

animesite/anime/templates/anime/add_new_anime.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>{{ title }}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.name_ru.label }}: </label>{{ form.name_ru }}</p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.name_en.label }}: </label>{{ form.name_en }}</p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.name_jp.label }}: </label>{{ form.name_jp }}</p>
            <p><label for="{{ form.image.id_for_label}} ">{{ form.image.label }}: </label>{{ form.image }}</p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.slug.label }}: </label>{{ form.slug }}</p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.genre.label }}: </label>{{ form.genre }}<a href="{% url 'add_new_genre' %}"><button type="button">Добавить жанр</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.episodes.label }}: </label>{{ form.episodes }}</p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.year.label }}: </label>{{ form.year }}<a href="{% url 'add_new_year' %}"><button type="button">Добавить год</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.producer.label }}: </label>{{ form.producer }}<a href="{% url 'add_new_producer' %}"><button type="button">Добавить режиссера</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.author.label }}: </label>{{ form.author }}<a href="{% url 'add_new_author' %}"><button type="button">Добавить автора оригинала</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.tag.label }}: </label>{{ form.tag }}<a href="{% url 'add_new_tag' %}"><button type="button">Добавить тег</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.studio.label }}: </label>{{ form.studio }}<a href="{% url 'add_new_studio' %}"><button type="button">Добавить студию</button></a></p>
            <p><label for="{{ form.name_ru.id_for_label}} ">{{ form.description.label }}: </label>{{ form.description }}</p>
            <button type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock content %}

animesite/anime/templates/anime/add_new_author.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>{{ title }}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock content %}

animesite/anime/templates/anime/add_new_genre.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>{{ title }}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock content %}

animesite/anime/templates/anime/add_new_studio.html
{% extends 'base.html' %}

{% block content %}
<div class="content-table">
    <div class="form-table-panel">
        <h1>{{ title }}</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </div>
</div>
{% endblock content %}

animesite/anime/templates/anime/addanime.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>

{% endblock content %}

animesite/anime/templates/anime/all_anime_page.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<h2>Поиск по названию</h2>

<form action="" method="get" >
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
</form>
{% endblock breadcrumbs %}

{% block content %}
{% include 'anime/show_anime_list_template.html' %}
{% endblock content %}

animesite/anime/templates/anime/anime_from_author_page.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<div class="link-edit">
    <div class="link-edit-breadcrumbs">
        <a href="{% url 'edit_author' author.author_slug %}">Редактировать автора: {{ author.name }}</a><a href="{% url 'add_new_author' %}">Добавить автора оригинала</a>
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
{% include 'anime/show_anime_list_template.html' %}
{% endblock content %}

animesite/anime/templates/anime/anime_from_genre_page.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<div class="link-edit">
    <div class="link-edit-breadcrumbs">
        {% if user.is_authenticated %}{% if perms.anime.add_genre %}
        <p><a href="{% url 'anime_from_genre_page' genre_slug %}">Редактировать жанр: {{ genre.name }}</a><a href="{% url 'add_new_genre' %}">Добавить жанр</a></p>
        {% endif %}{% endif %}
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
{% include 'anime/show_anime_list_template.html' %}
{% endblock content %}

animesite/anime/templates/anime/anime_from_year_page.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<div class="link-edit">
    <div class="link-edit-breadcrumbs">
        {% if user.is_authenticated %}{% if perms.anime.add_years %}
        <p><a href="{% url 'edit_year' year.year %}">Редактировать {{ year }} год</a><a href="{% url 'add_new_year' %}">Добавить год</a></p>
        {% endif %}{% endif %}
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
{% include 'anime/show_anime_list_template.html' %}
{% endblock content %}

animesite/anime/templates/anime/anime_year_page.html
{% extends 'base.html' %}

{% block content %}
{% for a in anime %}
<ul>
<li><a href="{{ a.get_absolute_url }}">{{ a.name_ru }}</a></li>
</ul>
{% endfor %}
{% endblock content %}

animesite/anime/templates/anime/producer_page.html
{% extends 'base.html' %}

{% block content %}
{% for a in anime %}
<ul>
<li><a href="{{ a.get_absolute_url }}">{{ a.name_ru }}</a></li>
</ul>
{% endfor %}
{% endblock content %}

animesite/anime/templates/anime/show_anime_list_template.html
<div>
{% for a in anime %}
<div class="content-table">
    <a href="{{ a.get_absolute_url }}"><img class="img-article-left" alt="" src="{{ a.image.url }}"></a>

        <h1 class="link-read"><a href="{{ a.get_absolute_url }}">{{ a.name_ru }}</a></h1>

        {% include 'anime/show_anime_tags_template.html' %}

        <p>{{ a.description|truncatewords:80 }}</p>

        {% include 'anime/show_anime_studio_template.html' %}

        <div class="cell-margin"><p class="link-edit" align="right"><a href="{{ a.get_absolute_url }}">Подробнее</a></p></div>

</div>
{% endfor %}
</div>

animesite/anime/templates/anime/show_anime_studio_template.html
{% with a.studio.all as studios %}
{% if studios %}
<div>
    {% for s in studios %}
        <a href="{{ s.get_absolute_url }}"><img class="img-logo-studio" src="{{ s.logo.url }}" alt="{{ s.name }}" title="{{ s.name }}"></a>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

animesite/anime/templates/anime/year_page.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<div class="link-edit">
    <div class="link-edit-breadcrumbs">
        {% if user.is_authenticated %}{% if perms.anime.add_years %}
        <p><a href="{% url 'add_new_year' %}">Добавить год</a></p>
        {% endif %}{% endif %}
    </div>
</div>
{% endblock breadcrumbs %}

{% block content %}
<div class="content-table">
{% for y in year %}
<div class="list-cell-margin">
    <div class="cell-margin">
        <a href="{{ y.get_absolute_url }}">{{ y }}</a>
    </div>
</div>
{% endfor %}
</div>
{% endblock content %}