animesite/animesite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from animesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('news.urls', namespace='news')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"

animesite/news/urls.py
from django.urls import path

from news import views

app_name = 'news'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('post/<slug:post_slug>/', views.PostPageView.as_view(), name='post_page'),
]

animesite/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login_user'),
    path('logout/', LogoutView.as_view(), name='logout_user'),

    path('registration/', views.RegistrationUserView.as_view(), name='registration'),
    path('registration_success/', views.registration_success, name='registration_success'),

    path('user_profile/', views.UserProfile.as_view(), name='user_profile'),

    path('user_profile/password_change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('user_profile/password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
                                            template_name='users/password_reset_form.html',
                                            email_template_name='users/password_reset_email.html',
                                            success_url=reverse_lazy('users:password_reset_done')
                                            ),
                                            name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
                                            template_name='users/password_reset_done.html'),
                                            name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                            template_name='users/password_reset_confirm.html',
                                            success_url=reverse_lazy('users:password_reset_complete')
                                            ),
                                            name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(
                                            template_name='users/password_reset_complete.html'),
                                            name='password_reset_complete'),
]

animesite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'anime/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'anime/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table align="center" width="70%">
	<tr>
		<td>
		{% block mainmenu %}
			<div class="header">
				<ul id="mainmenu" class="mainmenu">
				<li><a href="{% url 'news:index' %}"><div class="logo"></div></a></li>
			{% for m in mainmenu %}
				<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
			{% endfor %}
			{% if user.is_authenticated %}
				<li class="last"> <a href="{% url 'users:user_profile' %}"> {{ user.username }} | <a href="{% url 'users:logout_user' %}">Выйти</a></li>
			{% else %}
				<li class="last"><a href="{% url 'users:login_user' %}">Войти</a> | <a href="{% url 'users:registration' %}">Регистрация</a></li>
			{% endif %}
				</ul>
				<div class="clear"></div>
			</div>
		{% endblock mainmenu %}
		</td>
</tr>
<table align="center" width="70%">
	<tr>
		<td>
			{% block breadcrumbs %}
			{% endblock breadcrumbs %}
		</td>
	</tr>
	<tr>
		<td>
			<!-- Блок контента -->
			{% block content %}
			{% endblock %}
			<!-- Конец блока контента -->
		</td>
	</tr>
</table>

</table>
</body>
</html>